// <auto-generated />
using System;
using Discite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discite.Data.Migrations
{
    [DbContext(typeof(DisciteDbContext))]
    [Migration("20230121135408_PDMigration")]
    partial class PDMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Discite.Data.Models.ArtifactModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("int")
                        .HasColumnName("upgrade_level");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("artifact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxLevel = 3,
                            Name = "Flammable blood"
                        },
                        new
                        {
                            Id = 2,
                            MaxLevel = 3,
                            Name = "Poisonous blood"
                        },
                        new
                        {
                            Id = 3,
                            MaxLevel = 3,
                            Name = "Exploding corpses"
                        },
                        new
                        {
                            Id = 4,
                            MaxLevel = 3,
                            Name = "Revenge damage"
                        });
                });

            modelBuilder.Entity("Discite.Data.Models.ClassModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Damage")
                        .HasColumnType("float");

                    b.Property<float>("Energy")
                        .HasColumnType("float");

                    b.Property<float>("MaxHp")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<float>("Speed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 5f,
                            Energy = 160f,
                            MaxHp = 70f,
                            Name = "Artificier",
                            Speed = 1f
                        },
                        new
                        {
                            Id = 2,
                            Damage = 4f,
                            Energy = 100f,
                            MaxHp = 120f,
                            Name = "Weapon Master",
                            Speed = 1f
                        },
                        new
                        {
                            Id = 3,
                            Damage = 4f,
                            Energy = 130f,
                            MaxHp = 90f,
                            Name = "Cyber Ninja",
                            Speed = 2f
                        });
                });

            modelBuilder.Entity("Discite.Data.Models.EnemyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Damage")
                        .HasColumnType("float");

                    b.Property<float>("Energy")
                        .HasColumnType("float");

                    b.Property<float>("MaxHp")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<float>("Speed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("enemy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 10f,
                            Energy = 0f,
                            MaxHp = 20f,
                            Name = "Ghoul",
                            Speed = 0.7f
                        },
                        new
                        {
                            Id = 2,
                            Damage = 25f,
                            Energy = 0f,
                            MaxHp = 5f,
                            Name = "Exploder",
                            Speed = 1f
                        },
                        new
                        {
                            Id = 3,
                            Damage = 20f,
                            Energy = 0f,
                            MaxHp = 35f,
                            Name = "Cyber Ghoul",
                            Speed = 1.5f
                        },
                        new
                        {
                            Id = 4,
                            Damage = 10f,
                            Energy = 0f,
                            MaxHp = 60f,
                            Name = "Multi-tank",
                            Speed = 0.5f
                        },
                        new
                        {
                            Id = 5,
                            Damage = 15f,
                            Energy = 0f,
                            MaxHp = 20f,
                            Name = "Agent",
                            Speed = 0.7f
                        },
                        new
                        {
                            Id = 6,
                            Damage = 15f,
                            Energy = 0f,
                            MaxHp = 200f,
                            Name = "Chimera",
                            Speed = 1.2f
                        });
                });

            modelBuilder.Entity("Discite.Data.Models.RoomModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("eventroom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Entry room"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Exit room"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Encounter room"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shop room"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Boss room"
                        });
                });

            modelBuilder.Entity("Discite.Data.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Hash")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("register_date");

                    b.Property<string>("Salt")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user");
                });

            modelBuilder.Entity("Discite.Data.Models.WeaponModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("AttackSpeed")
                        .HasColumnType("float");

                    b.Property<float>("Damage")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("weapon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackSpeed = 1.5f,
                            Damage = 3f,
                            Name = "Katana"
                        },
                        new
                        {
                            Id = 2,
                            AttackSpeed = 1f,
                            Damage = 4f,
                            Name = "Spear"
                        },
                        new
                        {
                            Id = 3,
                            AttackSpeed = 0.7f,
                            Damage = 6f,
                            Name = "Deagle"
                        },
                        new
                        {
                            Id = 4,
                            AttackSpeed = 3f,
                            Damage = 1f,
                            Name = "Laser SMG"
                        },
                        new
                        {
                            Id = 5,
                            AttackSpeed = 0.5f,
                            Damage = 1f,
                            Name = "Shotgun"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
